// const express = require('express');
import express from 'express';
// const router = require('./routes/route');
import router from './routes/route';
const app = express();
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(router);
// module.exports = app;
export default app;